version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:4.4
    container_name: infrachat-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: infrachat
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - infrachat-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infrachat-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/infrachat?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - infrachat-network

volumes:
  mongodb_data:

networks:
  infrachat-network:
    driver: bridge
